#!/bin/sh -eux

# DCS updater download link
DCS_UPDATER_URL="https://cdn.digitalcombatsimulator.com/files/DCS_updater_64bit.zip"

# DCS updater likely requires a UTF-8 locale:
# https://github.com/ActiumDev/dcs-server-wine/issues/5#issuecomment-2869641405
if [ ${LANG%.UTF-8} = ${LANG} ] ; then
	echo "ERROR: The DCS updater requires a UTF-8 compatible locale, but your locale is not (\$LANG=$LANG)." >&2
	exit 1
fi

# need headless GUI session to run DCS installer
if ! systemctl --user --quiet is-active sway ; then
	echo "ERROR: Minimal GUI not running. Required to start DCS updater." >&2
	exit 1
fi

# redirect new windows to headless GUI session (winecfg)
export $(systemctl --user show-environment | grep -m1 ^WAYLAND_DISPLAY=)

# undo possibly counter-productive registry tweaks
# TODO: move to separate script and/or remove once obsolete
wine reg add "HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Services\\PlugPlay" /v Start /t REG_DWORD /d 0x03 /f
wine reg add "HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Services\\RpcSs" /v Start /t REG_DWORD /d 0x03 /f
wine reg delete "HKEY_CURRENT_USER\\Software\\Wine\\DllOverrides" /v "dxdiag.exe" /f || true
wine reg delete "HKEY_CURRENT_USER\\Software\\Wine\\DllOverrides" /v "rpcss.exe" /f || true
wine reg delete "HKEY_CURRENT_USER\\Software\\Wine\\DllOverrides" /v "services.exe" /f || true
wine reg delete "HKEY_CURRENT_USER\\Software\\Wine\\DllOverrides" /v "svchost.exe" /f || true
wine reg delete "HKEY_CURRENT_USER\\Software\\Wine\\DllOverrides" /v "winedevice.exe" /f || true

# if configuration directory is missing, populate it with defaults
# TODO: support this for multiple server instances (including port setup)
DCS_CFG_DIR=${WINEPREFIX:-$HOME/.wine}/drive_c/DCS_configs
if [ ! -e $DCS_CFG_DIR/DCS.server1 ] ; then
	cp -a $DCS_CFG_DIR/DCS_defaults $DCS_CFG_DIR/DCS.server1
fi

# populate $DCS_SRV_DIR like the modular dedicated server installer would:
#   * https://www.digitalcombatsimulator.com/en/downloads/world/server/
#   * https://forum.dcs.world/topic/324040-eagle-dynamics-modular-dedicated-server-installer/
DCS_SRV_DIR=${WINEPREFIX:-$HOME/.wine}/drive_c/DCS_server
mkdir -p $DCS_SRV_DIR/bin $DCS_SRV_DIR/Config
cd $DCS_SRV_DIR

# download DCS updater binary if needed
if [ ! -e $DCS_SRV_DIR/bin/DCS_updater.exe ] ; then
	DCS_UPDATER_ZIP=${DCS_UPDATER_URL##*/}
	curl -fOL "$DCS_UPDATER_URL"
	unzip $DCS_UPDATER_ZIP -d $DCS_SRV_DIR/bin
	rm $DCS_UPDATER_ZIP
fi

# (over)write static config files
echo -n "EN" >$DCS_SRV_DIR/Config/lang.txt
echo -n "dcs_server.release" >$DCS_SRV_DIR/dcs_variant.txt

# initialize autoupdate.cfg
# NOTE: do not overwrite existing autoupdate.cfg as it will contain "version"
#       and "timestamp" keys presumably relevant for the updater
if [ ! -e $DCS_SRV_DIR/autoupdate.cfg ] ; then
	# assemble list of terrains to install (default to installing Caucasus)
	TERRAINS_JSON=""
	for TERRAIN in ${DCS_TERRAINS:-CAUCASUS_terrain} ; do
		TERRAINS_JSON="$TERRAINS_JSON, \"$TERRAIN\""
	done

	# set "launch" key to null to prevent updater from starting server
	cat <<-EOF >$DCS_SRV_DIR/autoupdate.cfg
		{
		 "WARNING": "DO NOT EDIT this file. You may break your install!",
		 "branch": "dcs_server.release",
		 "arch": "x86_64",
		 "lang": "EN",
		 "modules": [
		  "WWII-ARMOUR", "SUPERCARRIER", "WORLD"$TERRAINS_JSON
		 ],
		 "launch": null
		}
	EOF
fi

# install DCS by running the updater: `wine bin/DCS_updater.exe --quiet update`
# updater is executed as background service (immune to SSH connection loss)
# for more information on DCS updater and its arguments, see:
#   * https://forum.dcs.world/topic/94816-guide-info-dcs-updater-usage-version-numbers-module-ids/
if ! systemctl --user start dcs-updater ; then
	systemctl --user --lines=100 status dcs-updater
	echo "ERROR: DCS updater failed" >&2
	exit 1
fi

# enable and start DCS server
systemctl --user enable --now dcs-server@server1
# verify it started successfully (may take a few seconds to fail)
sleep 10
if ! systemctl --user --quiet is-active dcs-server@server1 ; then
	systemctl --user --lines=100 status dcs-server@server1
	echo "ERROR: starting DCS dedicated server failed" >&2
	exit 1
fi
